### ISSUE TITLE
Chef doesn't spin up deployments containing ralf

### ISSUE THREAD

**Issue by mirw** [Metaswitch/chef#151]
Use chef to spin up a deployment containing ralf.  Ralf doesn't install correctly and sprout isn't configured to talk to it.  This is because `/etc/clearwater/config` has `ralf_hostname` set to blank.  This seems to be a result of https://github.com/Metaswitch/chef/commit/6633a4884f3848ec68ddc052963853805e82959e, where the `ralf` variable is only set if `node[:clearwater][:ralf] and node[:clearwater][:ralf] > 0` - I think this condition is wrong.

**Comment by mirw** [comment]
@eleanor-merry, please can you take a look at what the condition should have been?

**Comment by rkd-msw** [comment]
It looks as though https://github.com/Metaswitch/chef/commit/6633a4884f3848ec68ddc052963853805e82959e introduced a new requirement to have `"ralf" => 1" in the Chef environment file for Ralf to work. @eleanor-merry, does that sound right?

**Comment by mirw** [comment]
I think you could be right, but I still think that is wrong... unless we also update it when we do `knife deployment resize --ralf-count=...`

**Comment by rkd-msw** [comment]
Hmm. No, I think I'm wrong - it's all based off the `--ralf-count` option. That's plumbed through into the JSON attribute `:ralf` on the node.

It looks as though:
* creating a new deployment with `--ralf-count 1` works.
* creating a deployment with `--ralf-count 0`, then resizing it with `--ralf-count 1`, doesn't work - the Sprout nodes have the :ralf attribute set to 0 on creation, and that isn't updated on resize, so their ralf_hostname line is blank. But the Ralf nodes will spin up successfully.
* `knife box create ralf` doesn't work - it uses `config[:ralf]` but doesn't define a `--ralf` option, so the created box has no :ralf JSON attribute and therefore ralf_hostname is blank. (This is what I tried at first, which misled me.)
* creating a new deployment  with `--ralf-count 1` and a pre-https://github.com/Metaswitch/chef/commit/6633a4884f3848ec68ddc052963853805e82959e Chef codebase, then updating the cookbook and running `sudo chef-client` on all the nodes, won't work - they won't have had a :ralf attribute set at creation, and so their ralf_hostname line is blank.
* having "ralf => 1" in the Chef environment file works, because those are attribute overrides and that makes the :ralf attribute be 1

@mirw , does this match what you've seen? Your initial comment said the repro condition was "Use chef to spin up a deployment containing ralf" - I think you'd only see the situation you described if you did that with "knife deployment resize" and "knife box create ralf".

**Comment by mirw** [comment]
I think I may have hit bullet 4.
