### ISSUE TITLE
Signup_key does not appear to be propagated to AIO deployments

### ISSUE THREAD

**Issue by steelyvoid** [Metaswitch/chef#278]
My chef client has a signup_key in ~/.chef/knife.rb, configured as

```
# Signup key. Anyone with this key can create accounts
# on the deployment. Set to a secure value.
knife[:signup_key]        = "abcde"
```

However, that signup key doesn't appear to have been propagated to the AIO system I launched from the chef client (using "knife box create cw_aio..."), whose shared_config file contains

```
# Keys
signup_key=secret
```

I'm at commit 46094fb1d1fec7a98c94dc4074822169e9018e0c on my chef client

**Comment by graemerobertson** [comment]
This is deliberate (but not great IMO) - @rkd-msw to elaborate

**Comment by rkd-msw** [comment]
cw_aio nodes deliberately use https://github.com/Metaswitch/clearwater-infrastructure/blob/master/scripts/clearwater-aio-install.sh, rather than the standard Chef tools (which would set up the signup code from knife.rb), so that they're consistent with our OVA images. Those are more widely used, but more tedious to test, so having our EC2 AIO nodes be as similar as possible to them reduces the risk of bugs.

We made this change in https://github.com/Metaswitch/chef/commit/19283509370a68b03763f2caf29d9163d8dd8773#diff-6d7841c1e451607a203007493e7b8936.

Are you OK to close this?

**Comment by steelyvoid** [comment]
Works for me.  Alex, are you happy with this?

**Comment by AlexHockey** [comment]
We shouldn't reflexively close this. It has confused both me and Steve, and is counter-intuitive. As a user I expect that if I install from an image then the passwords will be defaulted. If I'm installing via chef I expect the configured password to be used. 

I appreciate why we've made this change but we should document it better. Maybe we could have the  chef script print a notice saying that the password isn't what you expect. We should also update readthedocs.
